export default [
  {
    login: "crystalguzman08",
    id: 86030906,
    node_id: "MDQ6VXNlcjg2MDMwOTA2",
    avatar_url: "https://avatars.githubusercontent.com/u/86030906?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/crystalguzman08",
    html_url: "https://github.com/crystalguzman08",
    followers_url: "https://api.github.com/users/crystalguzman08/followers",
    following_url:
      "https://api.github.com/users/crystalguzman08/following{/other_user}",
    gists_url: "https://api.github.com/users/crystalguzman08/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/crystalguzman08/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/crystalguzman08/subscriptions",
    organizations_url: "https://api.github.com/users/crystalguzman08/orgs",
    repos_url: "https://api.github.com/users/crystalguzman08/repos",
    events_url: "https://api.github.com/users/crystalguzman08/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/crystalguzman08/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ATOMRK",
    id: 94161843,
    node_id: "U_kgDOBZzLsw",
    avatar_url: "https://avatars.githubusercontent.com/u/94161843?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ATOMRK",
    html_url: "https://github.com/ATOMRK",
    followers_url: "https://api.github.com/users/ATOMRK/followers",
    following_url: "https://api.github.com/users/ATOMRK/following{/other_user}",
    gists_url: "https://api.github.com/users/ATOMRK/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ATOMRK/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ATOMRK/subscriptions",
    organizations_url: "https://api.github.com/users/ATOMRK/orgs",
    repos_url: "https://api.github.com/users/ATOMRK/repos",
    events_url: "https://api.github.com/users/ATOMRK/events{/privacy}",
    received_events_url: "https://api.github.com/users/ATOMRK/received_events",
    type: "User",
    site_admin: false,
  },
];
