export default {
  login: "Jeremy-Polanco",
  id: 85263988,
  node_id: "MDQ6VXNlcjg1MjYzOTg4",
  avatar_url: "https://avatars.githubusercontent.com/u/85263988?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Jeremy-Polanco",
  html_url: "https://github.com/Jeremy-Polanco",
  followers_url: "https://api.github.com/users/Jeremy-Polanco/followers",
  following_url:
    "https://api.github.com/users/Jeremy-Polanco/following{/other_user}",
  gists_url: "https://api.github.com/users/Jeremy-Polanco/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Jeremy-Polanco/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/Jeremy-Polanco/subscriptions",
  organizations_url: "https://api.github.com/users/Jeremy-Polanco/orgs",
  repos_url: "https://api.github.com/users/Jeremy-Polanco/repos",
  events_url: "https://api.github.com/users/Jeremy-Polanco/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Jeremy-Polanco/received_events",
  type: "User",
  site_admin: false,
  name: "Jeremy Polanco Lara",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: true,
  bio: "I'm a Software development student, whiling to learn new things.",
  twitter_username: null,
  public_repos: 15,
  public_gists: 0,
  followers: 2,
  following: 1,
  created_at: "2021-06-03T00:32:28Z",
  updated_at: "2022-04-17T00:13:32Z",
};
